# Generated by Django 2.2.10 on 2021-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doct', '0003_auto_20210826_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_took',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
